code is for python and markup is for html
# symbol for headings in markup mode
More no of # symbols decrese the font size
! symbol for batch commands
% symbol for linux commands
using kernel option, we can restart,reconnect, shoutdown etc.....

## List of batch commands

In [ ]:
!pip list

In [ ]:
!python -V

## List of linux commands

In [ ]:
%lsmagic

In [ ]:
%pwd

In [ ]:
%ls -la

In [1]:
import time
def trad_version():
    t1=time.time()
    X=range(100000000)
    Y=range(100000000)
    Z=[]
    for i in range(len(X)):
        Z.append(X[i]+Y[i])
    return time.time()-t1

print(trad_version())#84.30

83.80947613716125


In [2]:
import numpy as np
def numpy_version():
    t1=time.time()# takes time import from above cell
    X=np.arange(100000000)# just like range but it gives array not list
    Y=np.arange(100000000)
    Z=X+Y
    return time.time()-t1

print(numpy_version())#1.50

1.4443414211273193


In [ ]:
import sys
I=range(100000000)
print(sys.getsizeof(5)*len(I))#size of 100000000 elemts

In [ ]:
import sys
import numpy as np
arr=np.arange(100000000)
arr.size*arr.itemsize#size of 100000000 elemts

### 1. Creating numpy arrays

In [ ]:
import numpy as np
arr=np.array([1,2,3,4])# pass any iterable object
type(arr)


In [ ]:
arr.shape#dimesion

### 2.Numpy offers functions to create arrays with initial placeholder content

In [ ]:
array_of_zeroes=np.zeros((3,4))
array_of_zeroes

In [ ]:
array_of_onees=np.ones((4,4))# default element type is float
array_of_onees

In [ ]:
array_of_onees=np.ones((4,4),dtype=np.int16)
array_of_onees

In [ ]:
array_of_empty=np.empty((3,4))
array_of_empty

In [ ]:
array_of_eye=np.eye(3)
array_of_eye

In [ ]:
array_of_arange=np.arange(2,20,2)
array_of_arange

In [ ]:
array_of_float=np.arange(0,2,0.2)
array_of_float

In [ ]:
array_2d=np.array([[2,3,4],[5,6,7]])
array_2d

In [10]:
array_2d.shape

NameError: name 'array_2d' is not defined

In [15]:
np.arange(6).reshape(6,-230)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [19]:
np.arange(6).reshape(-1,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [20]:
np.arange(6).reshape(-1,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [21]:
np.arange(6).reshape(-1,5)

ValueError: cannot reshape array of size 6 into shape (5)

In [23]:
np.arange(6).reshape(-1,6)

array([[0, 1, 2, 3, 4, 5]])

In [24]:
np.arange(6).reshape(-1,0)

ValueError: cannot reshape array of size 6 into shape (0)

In [25]:
np.arange(6).reshape(3,1)

ValueError: cannot reshape array of size 6 into shape (3,1)

In [13]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [14]:
np.arange(6).shape

(6,)

#### using reshape we can create n dimesional arrays

In [4]:
array_nd=np.arange(6)
array_nd.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
array_nd.reshape(3,4)

In [27]:
array_ones=np.ones_like(array_nd)
array_ones

array([1, 1, 1, 1, 1, 1])

In [26]:
array_zeroes=np.zeros_like(array_nd.reshape(3,2))
array_zeroes 

array([[0, 0],
       [0, 0],
       [0, 0]])

In [ ]:
array_empty=np.empty_like(array_nd.reshape(3,2))
array_empty

In [28]:
array5=np.linspace(0,10,5)
array5

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [29]:
array6=np.diag([0,10,1,2,3,45])
array6

array([[ 0,  0,  0,  0,  0,  0],
       [ 0, 10,  0,  0,  0,  0],
       [ 0,  0,  1,  0,  0,  0],
       [ 0,  0,  0,  2,  0,  0],
       [ 0,  0,  0,  0,  3,  0],
       [ 0,  0,  0,  0,  0, 45]])

In [31]:
consMat=np.full(shape=(2,3),fill_value=5)
consMat

array([[5, 5, 5],
       [5, 5, 5]])

In [32]:
zerosMat=np.zeros(shape=(4,3),dtype='int16')
zerosMat

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int16)

In [33]:
eyeMat=np.eye(N=3,M=4)
eyeMat

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [34]:
randMat=np.random.rand((4,3))
randMat

TypeError: 'tuple' object cannot be interpreted as an integer

In [35]:
randMat=np.random.rand(4,3)
randMat

array([[0.27529463, 0.62516771, 0.50102603],
       [0.85477723, 0.06312384, 0.47738408],
       [0.84480684, 0.55247097, 0.26788854],
       [0.33260059, 0.15375045, 0.43940858]])

## 2D Array

In [ ]:
import numpy as np
b=np.arange(12).reshape(4,3)
b

In [ ]:
b[0]

In [ ]:
b[0][0]

## 3D Array

In [ ]:
import numpy as np
d3 = np.arange(16).reshape(2,2,4)
d3

In [ ]:
d3[1]

In [36]:
np.arange(10000)

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [37]:
np.arange(10000).reshape(100,100)

array([[   0,    1,    2, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  297,  298,  299],
       ...,
       [9700, 9701, 9702, ..., 9797, 9798, 9799],
       [9800, 9801, 9802, ..., 9897, 9898, 9899],
       [9900, 9901, 9902, ..., 9997, 9998, 9999]])

In [38]:
array1=np.array(object=[1,2,3],dtype='int')
array2=np.array([[1.5,2,3],[4,5,6],[7,8,9.5]],dtype='float')
array3=np.array([[(1.5,2,3),(4,5,6)],[(7,8,9.5),(4,5,8)]],dtype='int')

In [39]:
print("1-D --> {} \n2-D --> {}\n 3-D -->{}".format(array1,array2,array3))

1-D --> [1 2 3] 
2-D --> [[1.5 2.  3. ]
 [4.  5.  6. ]
 [7.  8.  9.5]]
 3-D -->[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [4 5 8]]]


In [40]:
print(type(array1),type(array2),type(array3))

<class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [41]:
print(array1.shape,array2.shape,array3.shape)

(3,) (3, 3) (2, 2, 3)


In [42]:
print(array1.size,array2.size,array3.size)

3 9 12


In [43]:
print(array1.dtype,array2.dtype,array3.dtype)

int32 float64 int32


In [47]:
array1=array1.astype('float')

In [48]:
print(array1.dtype,array2.dtype,array3.dtype)

float64 float64 int32


In [49]:
print(array1)

[1. 2. 3.]


In [50]:
print(array2)

[[1.5 2.  3. ]
 [4.  5.  6. ]
 [7.  8.  9.5]]


In [51]:
print(np.delete(arr=array2,obj=[0,2,4]))# obj is index of element one wnats to delete

[2.  4.  6.  7.  8.  9.5]


In [52]:
help(np.delete)

Help on function delete in module numpy.lib.function_base:

delete(arr, obj, axis=None)
    Return a new array with sub-arrays along an axis deleted. For a one
    dimensional array, this returns those entries not returned by
    `arr[obj]`.
    
    Parameters
    ----------
    arr : array_like
      Input array.
    obj : slice, int or array of ints
      Indicate which sub-arrays to remove.
    axis : int, optional
      The axis along which to delete the subarray defined by `obj`.
      If `axis` is None, `obj` is applied to the flattened array.
    
    Returns
    -------
    out : ndarray
        A copy of `arr` with the elements specified by `obj` removed. Note
        that `delete` does not occur in-place. If `axis` is None, `out` is
        a flattened array.
    
    See Also
    --------
    insert : Insert elements into an array.
    append : Append elements at the end of an array.
    
    Notes
    -----
    Often it is preferable to use a boolean mask. For example:
   

In [53]:
print(np.delete(arr=array2,obj=[0,2,4]).shape)

(6,)


In [54]:
array2

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ],
       [7. , 8. , 9.5]])

In [55]:
print(np.delete(arr=array2,obj=[1,2],axis=1))# if axis =0 ,obi is index of row;axis=1, obj is index of column

[[1.5]
 [4. ]
 [7. ]]


In [56]:
print(np.delete(arr=array2,obj=1,axis=0))

[[1.5 2.  3. ]
 [7.  8.  9.5]]
