In [4]:
import numpy as np

In [5]:
a= np.arange(11)**2

In [6]:
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [4]:
a[2]

4

In [5]:
a[-2]

81

In [6]:
a[2:7]

array([ 4,  9, 16, 25, 36], dtype=int32)

In [7]:
a[2:-2]

array([ 4,  9, 16, 25, 36, 49, 64], dtype=int32)

In [8]:
a[2:]

array([  4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [9]:
a[:7]

array([ 0,  1,  4,  9, 16, 25, 36], dtype=int32)

In [10]:
a[:11:2]

array([  0,   4,  16,  36,  64, 100], dtype=int32)

In [13]:
a[::-1]

array([100,  81,  64,  49,  36,  25,  16,   9,   4,   1,   0], dtype=int32)

In [16]:
a[-1:]

array([100], dtype=int32)

In [17]:
a[-1:-4]

array([], dtype=int32)

In [24]:
a[-1:-4:-1]

array([100,  81,  64], dtype=int32)

## 2D Array

Cosider an array students, it contains the test scores in two courses of the studets against their names

In [7]:
students=np.array([['Rocky','Shaggy','Edge','Mark'],
                  [65,78,90,81],
                  [71,82,79,92]])

In [28]:
students.dtype

dtype('<U6')

In [22]:
students.shape

(3, 4)

In [19]:
students

array([['Rocky', 'Shaggy', 'Edge', 'Mark'],
       ['65', '78', '90', '81'],
       ['71', '82', '79', '92']], dtype='<U6')

In [21]:
students[0]

array(['Rocky', 'Shaggy', 'Edge', 'Mark'], dtype='<U6')

In [23]:
students[1]

array(['65', '78', '90', '81'], dtype='<U6')

In [25]:
students[2]

array(['71', '82', '79', '92'], dtype='<U6')

In [26]:
students[0,1]

'Shaggy'

In [27]:
students[1,3]

'81'

### 2D Array slicing

In [ ]:
This will consider rows 0 and 1, columns 2 and 3 

In [30]:
students[0:2,2:4]

array([['Edge', 'Mark'],
       ['90', '81']], dtype='<U6')

In [13]:
students[:,1:2].shape

(3, 1)

In [14]:
students[:,1:2]

array([['Shaggy'],
       ['78'],
       ['82']], dtype='<U6')

In [15]:
students[:,1]

array(['Shaggy', '78', '82'], dtype='<U6')

In [33]:
students[:,1:3]

array([['Shaggy', 'Edge'],
       ['78', '90'],
       ['82', '79']], dtype='<U6')

In [34]:
students[0:2,1:]

array([['Shaggy', 'Edge', 'Mark'],
       ['78', '90', '81']], dtype='<U6')

In [36]:
students[:]

array([['Rocky', 'Shaggy', 'Edge', 'Mark'],
       ['65', '78', '90', '81'],
       ['71', '82', '79', '92']], dtype='<U6')

In [37]:
students[:-1]

array([['Rocky', 'Shaggy', 'Edge', 'Mark'],
       ['65', '78', '90', '81']], dtype='<U6')

In [38]:
students[::-1]

array([['71', '82', '79', '92'],
       ['65', '78', '90', '81'],
       ['Rocky', 'Shaggy', 'Edge', 'Mark']], dtype='<U6')

In [39]:
students[::-1,::-1]

array([['92', '79', '82', '71'],
       ['81', '90', '78', '65'],
       ['Mark', 'Edge', 'Shaggy', 'Rocky']], dtype='<U6')

In [40]:
students[-1:]

array([['71', '82', '79', '92']], dtype='<U6')

In [8]:
students[-1,:]

array(['71', '82', '79', '92'], dtype='<U6')

In [11]:
students[-3:-1,-2].shape

(2,)

In [12]:
students[-3:-1,-2]

array(['Edge', '90'], dtype='<U6')

In [10]:
students[-3:-1,-2:]

array([['Edge', 'Mark'],
       ['90', '81']], dtype='<U6')

## Dots and ellipsis(...)

In [ ]:
Equivalent to students[0] or studetns[0:1,:] 

In [46]:
students[0,...] 

array(['Rocky', 'Shaggy', 'Edge', 'Mark'], dtype='<U6')

In [47]:
students[...,1]#1D Array

array(['Shaggy', '78', '82'], dtype='<U6')

In [48]:
students[...,1].shape # Gives 1-D Array, if we use silicing it gives (3,1)

(3,)

In [49]:
students[:,1:2]#2D Array

array([['Shaggy'],
       ['78'],
       ['82']], dtype='<U6')

In [50]:
students[:,1:2].shape

(3, 1)

In [51]:
randMat=np.random.rand(4,3)
randMat

array([[0.66383553, 0.50249758, 0.82976932],
       [0.54549063, 0.9295185 , 0.88789917],
       [0.64397298, 0.39263929, 0.71081519],
       [0.28935873, 0.60656404, 0.39291522]])

In [52]:
randMat[0,1]

0.5024975817821914

In [53]:
print(randMat[0],randMat[0,:])

[0.66383553 0.50249758 0.82976932] [0.66383553 0.50249758 0.82976932]


In [54]:
randMat[...,...]

IndexError: an index can only have a single ellipsis ('...')

In [55]:
randMat[:,0]

array([0.66383553, 0.54549063, 0.64397298, 0.28935873])

In [56]:
randMat[:,0].shape

(4,)

In [57]:
randMat[1,:]=0
randMat

array([[0.66383553, 0.50249758, 0.82976932],
       [0.        , 0.        , 0.        ],
       [0.64397298, 0.39263929, 0.71081519],
       [0.28935873, 0.60656404, 0.39291522]])

In [58]:
randMat[0:2]

array([[0.66383553, 0.50249758, 0.82976932],
       [0.        , 0.        , 0.        ]])

In [59]:
randMat[0:2,]

array([[0.66383553, 0.50249758, 0.82976932],
       [0.        , 0.        , 0.        ]])

In [61]:
randMat[[0,2,3]]# slicing multiple rows at random positions----passing row indicies using array of indexes

array([[0.66383553, 0.50249758, 0.82976932],
       [0.64397298, 0.39263929, 0.71081519],
       [0.28935873, 0.60656404, 0.39291522]])

In [62]:
randMat[0,2,3]

IndexError: too many indices for array

In [63]:
randMat[0:2,0:2]

array([[0.66383553, 0.50249758],
       [0.        , 0.        ]])

In [64]:
randMat[-1]

array([0.28935873, 0.60656404, 0.39291522])

In [65]:
randMat[::1,::2]

array([[0.66383553, 0.82976932],
       [0.        , 0.        ],
       [0.64397298, 0.71081519],
       [0.28935873, 0.39291522]])

## 3-D Array

In [10]:
import numpy as np
arr3= np.array([[(1.6,2,3),(4,5,6)],[(3,2,1),(5,5,8)]],dtype='int') #3-D Array

In [15]:
arr3.shape

(2, 2, 3)

In [11]:
arr3[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
arr3[0,0]

array([1, 2, 3])

In [13]:
arr3[0,0:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
arr3[0,0:2,:1]

array([[1],
       [4]])

In [16]:
arr3[0,0:2,1] #if slicing is not used, then output will be in row format

array([2, 5])

In [17]:
arr3[0][0:2,:1]

array([[1],
       [4]])

In [18]:
arr3[0,1]

array([4, 5, 6])

In [19]:
arr3[1][:,1]

array([2, 5])

In [20]:
print(arr3[1][:,1])

[2 5]


In [21]:
arr=np.array([1,2,3,4])

In [22]:
arr.shape

(4,)

In [23]:
arr.size

4

In [24]:
arr.dtype

dtype('int32')

In [27]:
arr.dtype.name # it is usefull with U1,U2.....

'int32'

In [28]:
for value in arr:
    print(value)

1
2
3
4


In [29]:
arr.ndim # gives dimension

1

In [30]:
arr3.ndim

3

In [39]:
array1=np.arange(10)

In [48]:
array1.ndim

1

In [49]:
array1.shape

(10,)

In [41]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
array_2d=array1.reshape(2,5)

In [47]:
for row in array_2d:
    print(row)

[0 1 2 3 4]
[5 6 7 8 9]


In [56]:
arr_flatten=array_2d.flatten(order='f')

In [57]:
arr_flatten

array([0, 5, 1, 6, 2, 7, 3, 8, 4, 9])

In [59]:
arr_flatten.shape

(10,)

In [67]:
arr_flatten_c=array_2d.flatten(order='C')

In [68]:
arr_flatten_c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
for i in np.nditer(arr_flatten_c):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [72]:
for i in np.nditer(arr_flatten):
    print(i)

0
5
1
6
2
7
3
8
4
9


In [78]:
for i in np.nditer(array_2d,order='F'): #if 'f' is small,ValueError: order must be one of 'C', 'F', 'A', or 'K'
    print(i)

0
5
1
6
2
7
3
8
4
9


In [82]:
dir(np.nditer)

['__class__',
 '__copy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__enter__',
 '__eq__',
 '__exit__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__next__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'close',
 'copy',
 'debug_print',
 'dtypes',
 'enable_external_loop',
 'finished',
 'has_delayed_bufalloc',
 'has_index',
 'has_multi_index',
 'index',
 'iterationneedsapi',
 'iterindex',
 'iternext',
 'iterrange',
 'itersize',
 'itviews',
 'multi_index',
 'ndim',
 'nop',
 'operands',
 'remove_axis',
 'remove_multi_index',
 'reset',
 'shape',
 'value']

In [83]:
help(np.nditer)

Help on class nditer in module numpy:

class nditer(builtins.object)
 |  Efficient multi-dimensional iterator object to iterate over arrays.
 |  To get started using this object, see the
 |  :ref:`introductory guide to array iteration <arrays.nditer>`.
 |  
 |  Parameters
 |  ----------
 |  op : ndarray or sequence of array_like
 |      The array(s) to iterate over.
 |  flags : sequence of str, optional
 |      Flags to control the behavior of the iterator.
 |  
 |        * "buffered" enables buffering when required.
 |        * "c_index" causes a C-order index to be tracked.
 |        * "f_index" causes a Fortran-order index to be tracked.
 |        * "multi_index" causes a multi-index, or a tuple of indices
 |          with one per iteration dimension, to be tracked.
 |        * "common_dtype" causes all the operands to be converted to
 |          a common data type, with copying or buffering as necessary.
 |        * "copy_if_overlap" causes the iterator to determine if read
 |     

In [86]:
for i in np.nditer(array_2d,order='F',flags=["external_loop"]):
    print(i)

[0 5]
[1 6]
[2 7]
[3 8]
[4 9]


In [89]:
array_2d_T=array_2d.T #Transpose

In [90]:
array_2d_T.shape

(5, 2)

In [91]:
array_2d_T.ndim

2

In [92]:
array_2d_T.size

10

In [93]:
arr_1D=np.arange(10)

In [94]:
np.split(arr_1D,3) #ValueError: array split does not result in an equal division

ValueError: array split does not result in an equal division

In [95]:
np.split(arr_1D,2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [96]:
np.split(arr_1D,5)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [97]:
np.split(arr_1D,[4,6])

[array([0, 1, 2, 3]), array([4, 5]), array([6, 7, 8, 9])]

In [98]:
np.split(arr_1D,[4,5,9]) # passing vlues to split

[array([0, 1, 2, 3]), array([4]), array([5, 6, 7, 8]), array([9])]

In [4]:
arr_2d_std=np.array([('Ram',"Sam","Raj","Manju"),('Maths',"Phy","Chemistry",'English')])

In [4]:
np.hsplit(arr_2d_std,2) #spliting horizontal row wise

[array([['Ram', 'Sam'],
        ['Maths', 'Phy']], dtype='<U9'), array([['Raj', 'Manju'],
        ['Chemistry', 'English']], dtype='<U9')]

In [5]:
arr_sr=np.vsplit(arr_2d_std,2) #spliting vertical column wise

In [6]:
arr_sr

[array([['Ram', 'Sam', 'Raj', 'Manju']], dtype='<U9'),
 array([['Maths', 'Phy', 'Chemistry', 'English']], dtype='<U9')]

In [107]:
arr_sr.shape

AttributeError: 'list' object has no attribute 'shape'

In [109]:
type(arr_sr)

list

In [5]:
name,sub=arr_2d_std

In [6]:
print(name)
print(sub)

['Ram' 'Sam' 'Raj' 'Manju']
['Maths' 'Phy' 'Chemistry' 'English']


In [117]:
np.vsplit(arr_2d_std,1)

[array([['Ram', 'Sam', 'Raj', 'Manju'],
        ['Maths', 'Phy', 'Chemistry', 'English']], dtype='<U9')]