# Array attributes

### Array attributes reflect information that is intrinsic to the array itself. Generally, accessing an array through its attributes allows you to get and sometimes set intrinsic properties of the array without creating a new array. The exposed attributes are the core parts of an array and only some of them can be reset meaningfully without creating a new array

## Memory layout

## ndarray.flags

### Information about the memory layout of the array.

## numpy.ndarray.shape

### Tuple of array dimensions.

#### The shape property is usually used to get the current shape of an array, but may also be used to reshape the array in-place by assigning a tuple of array dimensions to it. As with numpy.reshape, one of the new shape dimensions can be -1, in which case its value is inferred from the size of the array and the remaining dimensions. Reshaping an array in-place will fail if a copy is required

In [49]:
x = np.array([1, 2, 3, 4])

In [50]:
x.shape

(4,)

In [51]:
y = np.zeros((2, 3, 4))

In [52]:
y.shape

(2, 3, 4)

In [53]:
y

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [54]:
y.shape = (3, 8)

In [55]:
y

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [56]:
y.shape = (3, 6)

ValueError: cannot reshape array of size 24 into shape (3,6)

In [58]:
np.zeros((4,2))[::2].shape = (-1,) #Reshaping an array in-place will fail if a copy is required

AttributeError: incompatible shape for a non-contiguous array

In [60]:
np.zeros((4,2)).shape = (-1,)

In [61]:
np.zeros((4,2))[::2]

array([[0., 0.],
       [0., 0.]])

In [63]:
np.zeros((4,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

## ndarray.strides

### Tuple of bytes to step in each dimension when traversing an array.
### The byte offset of element (i[0], i[1], ..., i[n]) in an array a is:offset = sum(np.array(i) * a.strides)

#### Imagine an array of 32-bit integers (each 4 bytes)

In [2]:
import numpy as np
x = np.array([[0, 1, 2, 3, 4],
              [5, 6, 7, 8, 9]], dtype=np.int32)

#### This array is stored in memory as 40 bytes, one after the other (known as a contiguous block of memory). The strides of an array tell us how many bytes we have to skip in memory to move to the next position along a certain axis. For example, we have to skip 4 bytes (1 value) to move to the next column, but 20 bytes (5 values) to get to the same position in the next row. As such, the strides for the array x will be (20, 4)

In [13]:
array = np.arange(2*3*4)

In [14]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [15]:
type(array)

numpy.ndarray

In [16]:
y = np.reshape(array,(2,3,4))

In [17]:
y

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [18]:
y.strides

(48, 16, 4)

In [19]:
y[1,1,1]

17

In [20]:
np.array((1,1,1))

array([1, 1, 1])

In [21]:
offset = sum(y.strides * np.array((1,1,1)))

In [22]:
offset

68

In [23]:
offset/y.itemsize

17.0

In [24]:
y.strides * np.array((1,1,1))

array([48, 16,  4])

In [25]:
x = np.array(np.random.rand(2*3*4))

In [26]:
x

array([0.48665214, 0.7624919 , 0.16293696, 0.95178973, 0.08002637,
       0.72701215, 0.9811412 , 0.24562594, 0.27588294, 0.3328643 ,
       0.67336471, 0.31982554, 0.10946833, 0.64376135, 0.34427884,
       0.95903967, 0.2537447 , 0.5736685 , 0.52788233, 0.67147736,
       0.11507037, 0.95327368, 0.72924608, 0.12115159])

In [27]:
y1 = np.reshape(x ,(2,3,4))

In [28]:
y1.strides

(96, 32, 8)

In [29]:
y1.itemsize

8

In [30]:
offset1 = sum(y1.strides * np.array((1,1,1)))

In [31]:
offset1

136

In [32]:
y1[1,1,1]

0.5736685033201349

In [33]:
offset1/y1.itemsize

17.0

In [34]:
np.reshape(np.arange(2*3*2),(2,3,2))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [35]:
np.reshape(np.arange(2*3*2),(2,3,2)).transpose(0,1,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [36]:
np.reshape(np.arange(2*3*2),(2,3,2)).transpose(0,2,1)

array([[[ 0,  2,  4],
        [ 1,  3,  5]],

       [[ 6,  8, 10],
        [ 7,  9, 11]]])

In [37]:
np.reshape(np.arange(2*3*2),(2,3,2)).transpose(2,0,1)

array([[[ 0,  2,  4],
        [ 6,  8, 10]],

       [[ 1,  3,  5],
        [ 7,  9, 11]]])

In [38]:
np.reshape(np.arange(2*3*2),(2,3,2)).transpose(1,2,0)

array([[[ 0,  6],
        [ 1,  7]],

       [[ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11]]])

In [39]:
z = np.reshape(np.arange(2*3*2),(2,3,2)).transpose(0,2,1)

In [44]:
z.strides

(24, 4, 8)

In [45]:
z

array([[[ 0,  2,  4],
        [ 1,  3,  5]],

       [[ 6,  8, 10],
        [ 7,  9, 11]]])

In [46]:
offset3 = sum(z.strides * np.array([1,1,2]))

In [47]:
offset3/z.itemsize

11.0

In [48]:
z[1,1,2]

11

## ndarray.ndim

### Number of array dimensions

In [ ]:
import numpy as np

In [3]:
y = np.arange(10)

In [4]:
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
y.ndim

1

In [6]:
z = np.zeros((2,3,4))

In [7]:
z

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [8]:
z.ndim

3

## ndarray.data

### Python buffer object pointing to the start of the array’s data. The data pointer indicates the memory address of the first byte in the array

In [10]:
z.data

## ndarray.size

###  Number of elements in the array

In [16]:
z.size

24

In [17]:
np.prod(z.shape)

24

In [21]:
type(np.prod(z.shape)) #returns an instance of np.int_

numpy.int32

In [22]:
type(z.size) # a.size returns a standard arbitrary precision Python integer

int

## ndarray.itemsize

### Length of one array element in bytes

In [23]:
z.itemsize

8

## ndarray.nbytes

### Total bytes consumed by the elements of the array. Does not include memory consumed by non-element attributes of the array object.

In [14]:
z.nbytes

192

In [15]:
z.size * z.itemsize

192

## ndarray.base

### Base object if memory is from some other object.

In [25]:
z.base #The base of an array that owns its memory is None

In [26]:
z.base is None

True

In [27]:
cpy = z[::2]

In [28]:
cpy

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [29]:
z

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [30]:
cpy.base

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [33]:
cpy.base is z # Slicing creates a view, whose memory is shared with cpy

True

# Data type

## ndarray.dtype

### Data-type of the array’s elements. The data type object associated with the array can be found in the dtype attribute

In [32]:
z.dtype

dtype('float64')

# Other attributes

## ndarray.T

### The transposed array. Same as self.transpose().

In [34]:
z.T

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [35]:
z

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [40]:
z.T.shape

(4, 3, 2)

In [38]:
y.T

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
y.T.shape

(10,)

In [44]:
y.shape


(10,)

In [45]:
y.reshape(5,1)

ValueError: cannot reshape array of size 10 into shape (5,1)

In [46]:
y.reshape(10,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [49]:
y.reshape(10,1).T

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [48]:
y.reshape(10,1).T.shape

(1, 10)

In [42]:
y.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [43]:
y.reshape(5,2).T

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

## numpy.ndarray.real

### The real part of the array. numpy.real equivalent function

In [50]:
x = np.sqrt([1+0j, 0+1j])

In [51]:
x.real

array([1.        , 0.70710678])

In [52]:
x.real.dtype

dtype('float64')

## numpy.ndarray.imag

### the imaginary part of the array.

In [54]:
x.imag

array([0.        , 0.70710678])

In [55]:
x.imag.dtype

dtype('float64')