# Array attributes

### Array attributes reflect information that is intrinsic to the array itself. Generally, accessing an array through its attributes allows you to get and sometimes set intrinsic properties of the array without creating a new array. The exposed attributes are the core parts of an array and only some of them can be reset meaningfully without creating a new array

## Memory layout

## ndarray.flags

### Information about the memory layout of the array.

#### The flags object can be accessed dictionary-like (as in a.flags['WRITEABLE']), or by using lowercased attribute names (as in a.flags.writeable). Short flag names are only supported in dictionary access. 

#### Array flags provide information about how the memory area used for the array is to be interpreted. There are 7 Boolean flags in use, only four of which can be changed by the user: WRITEBACKIFCOPY, UPDATEIFCOPY, WRITEABLE, and ALIGNED  via direct assignment to the attribute or dictionary entry, or by calling ndarray.setflags

#### The array flags cannot be set arbitrarily:
#### 1. UPDATEIFCOPY can only be set False.
#### 2. WRITEBACKIFCOPY can only be set False.
#### 3. ALIGNED can only be set True if the data is truly aligned. The ALIGNED flag can only be set to True if the data is actually aligned according to the type
#### 4. WRITEABLE can only be set True if the array owns its own memory or the ultimate owner of the memory exposes a writeable buffer interface or is a string. The exception for string is made so that unpickling can be done without copying memory.

### Falgs Attributes

#### 1. C_CONTIGUOUS (C) - The data is in a single, C-style contiguous segment.
#### 2. F_CONTIGUOUS (F) - The data is in a single, Fortran-style contiguous segment.
#### 3. OWNDATA (O) - The array owns the memory it uses or borrows it from another object.
#### 4. WRITEABLE (W) - The data area can be written to. Setting this to False locks the data, making it read-only. A view (slice, etc.) inherits WRITEABLE from its base array at creation time, but a view of a writeable array may be subsequently locked while the base array remains writeable. (The opposite is not true, in that a view of a locked array may not be made writeable. However, currently, locking a base object does not lock any views that already reference it, so under that circumstance it is possible to alter the contents of a locked array via a previously created writeable view onto it.) Attempting to change a non-writeable array raises a RuntimeError exception.
#### 5. ALIGNED (A) - The data and all elements are aligned appropriately for the hardware.
#### 6. WRITEBACKIFCOPY (X) - This array is a copy of some other array. The C-API function PyArray_ResolveWritebackIfCopy must be called before deallocating to the base array will be updated with the contents of this array.
#### 7. UPDATEIFCOPY (U) - (Deprecated, use WRITEBACKIFCOPY) This array is a copy of some other array. When this array is deallocated, the base array will be updated with the contents of this array.
#### 8. FNC - F_CONTIGUOUS and not C_CONTIGUOUS.
#### 9 . FORC - F_CONTIGUOUS or C_CONTIGUOUS (one-segment test).
#### 10. BEHAVED (B) - ALIGNED and WRITEABLE.
#### 11. CARRAY (CA) - BEHAVED and C_CONTIGUOUS.
#### 12. FARRAY (FA) - BEHAVED and F_CONTIGUOUS and not C_CONTIGUOUS.

## numpy.ndarray.setflags

#### ndarray.setflags(write=None, align=None, uic=None)

#### Parameters:	
#### write : bool, optional - Describes whether or not a can be written to.
#### align : bool, optional - Describes whether or not a is aligned properly for its type.
#### uic : bool, optional - Describes whether or not a is a copy of another “base” array.

In [65]:
y = np.array([[3, 1, 7],
              [2, 0, 0],
              [8, 5, 9]])

In [66]:
y

array([[3, 1, 7],
       [2, 0, 0],
       [8, 5, 9]])

In [67]:
y.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [68]:
y.setflags(write=0 , align=0)

In [69]:
y.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : False
  ALIGNED : False
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [70]:
y.setflags(uic=1)

ValueError: cannot set WRITEBACKIFCOPY flag to True

## numpy.ndarray.shape

### Tuple of array dimensions.

#### The shape property is usually used to get the current shape of an array, but may also be used to reshape the array in-place by assigning a tuple of array dimensions to it. As with numpy.reshape, one of the new shape dimensions can be -1, in which case its value is inferred from the size of the array and the remaining dimensions. Reshaping an array in-place will fail if a copy is required

In [49]:
x = np.array([1, 2, 3, 4])

In [50]:
x.shape

(4,)

In [51]:
y = np.zeros((2, 3, 4))

In [52]:
y.shape

(2, 3, 4)

In [53]:
y

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [54]:
y.shape = (3, 8)

In [55]:
y

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [56]:
y.shape = (3, 6)

ValueError: cannot reshape array of size 24 into shape (3,6)

In [58]:
np.zeros((4,2))[::2].shape = (-1,) #Reshaping an array in-place will fail if a copy is required

AttributeError: incompatible shape for a non-contiguous array

In [60]:
np.zeros((4,2)).shape = (-1,)

In [61]:
np.zeros((4,2))[::2]

array([[0., 0.],
       [0., 0.]])

In [63]:
np.zeros((4,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

## ndarray.strides

### Tuple of bytes to step in each dimension when traversing an array.
### The byte offset of element (i[0], i[1], ..., i[n]) in an array a is:offset = sum(np.array(i) * a.strides)

#### Imagine an array of 32-bit integers (each 4 bytes)

In [2]:
import numpy as np
x = np.array([[0, 1, 2, 3, 4],
              [5, 6, 7, 8, 9]], dtype=np.int32)

#### This array is stored in memory as 40 bytes, one after the other (known as a contiguous block of memory). The strides of an array tell us how many bytes we have to skip in memory to move to the next position along a certain axis. For example, we have to skip 4 bytes (1 value) to move to the next column, but 20 bytes (5 values) to get to the same position in the next row. As such, the strides for the array x will be (20, 4)

In [13]:
array = np.arange(2*3*4)

In [14]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [15]:
type(array)

numpy.ndarray

In [16]:
y = np.reshape(array,(2,3,4))

In [17]:
y

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [18]:
y.strides

(48, 16, 4)

In [19]:
y[1,1,1]

17

In [20]:
np.array((1,1,1))

array([1, 1, 1])

In [21]:
offset = sum(y.strides * np.array((1,1,1)))

In [22]:
offset

68

In [23]:
offset/y.itemsize

17.0

In [24]:
y.strides * np.array((1,1,1))

array([48, 16,  4])

In [25]:
x = np.array(np.random.rand(2*3*4))

In [26]:
x

array([0.48665214, 0.7624919 , 0.16293696, 0.95178973, 0.08002637,
       0.72701215, 0.9811412 , 0.24562594, 0.27588294, 0.3328643 ,
       0.67336471, 0.31982554, 0.10946833, 0.64376135, 0.34427884,
       0.95903967, 0.2537447 , 0.5736685 , 0.52788233, 0.67147736,
       0.11507037, 0.95327368, 0.72924608, 0.12115159])

In [27]:
y1 = np.reshape(x ,(2,3,4))

In [28]:
y1.strides

(96, 32, 8)

In [29]:
y1.itemsize

8

In [30]:
offset1 = sum(y1.strides * np.array((1,1,1)))

In [31]:
offset1

136

In [32]:
y1[1,1,1]

0.5736685033201349

In [33]:
offset1/y1.itemsize

17.0

In [34]:
np.reshape(np.arange(2*3*2),(2,3,2))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [35]:
np.reshape(np.arange(2*3*2),(2,3,2)).transpose(0,1,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [36]:
np.reshape(np.arange(2*3*2),(2,3,2)).transpose(0,2,1)

array([[[ 0,  2,  4],
        [ 1,  3,  5]],

       [[ 6,  8, 10],
        [ 7,  9, 11]]])

In [37]:
np.reshape(np.arange(2*3*2),(2,3,2)).transpose(2,0,1)

array([[[ 0,  2,  4],
        [ 6,  8, 10]],

       [[ 1,  3,  5],
        [ 7,  9, 11]]])

In [38]:
np.reshape(np.arange(2*3*2),(2,3,2)).transpose(1,2,0)

array([[[ 0,  6],
        [ 1,  7]],

       [[ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11]]])

In [39]:
z = np.reshape(np.arange(2*3*2),(2,3,2)).transpose(0,2,1)

In [44]:
z.strides

(24, 4, 8)

In [45]:
z

array([[[ 0,  2,  4],
        [ 1,  3,  5]],

       [[ 6,  8, 10],
        [ 7,  9, 11]]])

In [46]:
offset3 = sum(z.strides * np.array([1,1,2]))

In [47]:
offset3/z.itemsize

11.0

In [48]:
z[1,1,2]

11

## ndarray.ndim

### Number of array dimensions

In [ ]:
import numpy as np

In [3]:
y = np.arange(10)

In [4]:
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
y.ndim

1

In [6]:
z = np.zeros((2,3,4))

In [7]:
z

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [8]:
z.ndim

3

## ndarray.data

### Python buffer object pointing to the start of the array’s data. The data pointer indicates the memory address of the first byte in the array

In [10]:
z.data

## ndarray.size

###  Number of elements in the array

In [16]:
z.size

24

In [17]:
np.prod(z.shape)

24

In [21]:
type(np.prod(z.shape)) #returns an instance of np.int_

numpy.int32

In [22]:
type(z.size) # a.size returns a standard arbitrary precision Python integer

int

## ndarray.itemsize

### Length of one array element in bytes

In [23]:
z.itemsize

8

## ndarray.nbytes

### Total bytes consumed by the elements of the array. Does not include memory consumed by non-element attributes of the array object.

In [14]:
z.nbytes

192

In [15]:
z.size * z.itemsize

192

## ndarray.base

### Base object if memory is from some other object.

In [25]:
z.base #The base of an array that owns its memory is None

In [26]:
z.base is None

True

In [27]:
cpy = z[::2]

In [28]:
cpy

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [29]:
z

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [30]:
cpy.base

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [33]:
cpy.base is z # Slicing creates a view, whose memory is shared with cpy

True

# Data type

## ndarray.dtype

### Data-type of the array’s elements. The data type object associated with the array can be found in the dtype attribute

In [32]:
z.dtype

dtype('float64')

# Other attributes

## ndarray.T

### The transposed array. Same as self.transpose().

In [34]:
z.T

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [35]:
z

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [40]:
z.T.shape

(4, 3, 2)

In [38]:
y.T

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
y.T.shape

(10,)

In [44]:
y.shape


(10,)

In [45]:
y.reshape(5,1)

ValueError: cannot reshape array of size 10 into shape (5,1)

In [46]:
y.reshape(10,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [49]:
y.reshape(10,1).T

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [48]:
y.reshape(10,1).T.shape

(1, 10)

In [42]:
y.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [43]:
y.reshape(5,2).T

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

## numpy.ndarray.real

### The real part of the array. numpy.real equivalent function

In [50]:
x = np.sqrt([1+0j, 0+1j])

In [51]:
x.real

array([1.        , 0.70710678])

In [52]:
x.real.dtype

dtype('float64')

## numpy.ndarray.imag

### the imaginary part of the array.

In [54]:
x.imag

array([0.        , 0.70710678])

In [55]:
x.imag.dtype

dtype('float64')

## ndarray.flat

### A 1-D iterator over the array.This is a numpy.flatiter instance, which acts similarly to, but is not a subclass of, Python’s built-in iterator object.

In [71]:
y = np.arange(1, 7).reshape(2, 3)

In [72]:
y

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
y.flat

In [74]:
type(y.flat)

numpy.flatiter

In [76]:
y.flat[3]

4

In [78]:
y.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [80]:
y.T.flat[3]

5

In [81]:
y.flat = 3

In [82]:
y

array([[3, 3, 3],
       [3, 3, 3]])

In [83]:
y.flat[[1,4]] = 1

In [84]:
y

array([[3, 1, 3],
       [3, 1, 3]])

## numpy.flatiter

### class numpy.flatiter - Flat iterator object to iterate over arrays.

#### A flatiter iterator can not be constructed directly from Python code by calling the flatiter constructor. It allows iterating over the array as if it were a 1-D array, either in a for-loop or by calling its next method. Iteration is done in row-major, C-style order (the last index varying the fastest). The iterator can also be indexed using basic slicing or advanced indexing

In [91]:
x = np.arange(6).reshape(2,3)

In [92]:
f1 = x.flat
type(f1)

numpy.flatiter

In [93]:
for item in f1:
    print(item)

0
1
2
3
4
5


In [95]:
f1[2:4]

array([2, 3])

### Attributes:	
#### 1. base - A reference to the array that is iterated over.
#### 2. coords - An N-dimensional tuple of current coordinates.
#### 3 .index - Current flat index into the array.

In [102]:
x = np.arange(6).reshape(2,3)
f1 = x.flat
fl.base is x

False

In [108]:
print(f1.coords)
print(f1.index)

(0, 0)
0


In [116]:
f1.next()

AttributeError: 'numpy.flatiter' object has no attribute 'next'

In [117]:
f1.__next__()

0

In [118]:
print(f1.coords)
print(f1.index)

(0, 1)
1


In [112]:
x

array([[0, 1, 2],
       [3, 4, 5]])

In [113]:
f1.copy()

array([0, 1, 2, 3, 4, 5])