## ndarray.ndim

### Number of array dimensions

In [ ]:
import numpy as np

In [3]:
y = np.arange(10)

In [4]:
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
y.ndim

1

In [6]:
z = np.zeros((2,3,4))

In [7]:
z

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [8]:
z.ndim

3

## ndarray.data

### Python buffer object pointing to the start of the array’s data. The data pointer indicates the memory address of the first byte in the array

In [10]:
z.data

## ndarray.size

###  Number of elements in the array

In [16]:
z.size

24

In [17]:
np.prod(z.shape)

24

In [21]:
type(np.prod(z.shape)) #returns an instance of np.int_

numpy.int32

In [22]:
type(z.size) # a.size returns a standard arbitrary precision Python integer

int

## ndarray.itemsize

### Length of one array element in bytes

In [23]:
z.itemsize

8

## ndarray.nbytes

### Total bytes consumed by the elements of the array. Does not include memory consumed by non-element attributes of the array object.

In [14]:
z.nbytes

192

In [15]:
z.size * z.itemsize

192

## ndarray.base

### Base object if memory is from some other object.

In [25]:
z.base #The base of an array that owns its memory is None

In [26]:
z.base is None

True

In [27]:
cpy = z[::2]

In [28]:
cpy

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [29]:
z

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [30]:
cpy.base

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [31]:
cpy.base is z # Slicing creates a view, whose memory is shared with cpy

True

## ndarray.dtype

### Data-type of the array’s elements. The data type object associated with the array can be found in the dtype attribute

In [32]:
z.dtype

dtype('float64')