In [1]:
import numpy as np

In [2]:
x =  np.array([1,2,3,4,5])

In [3]:
x 

array([1, 2, 3, 4, 5])

In [6]:
y = np.ndarray(shape=(2,2), dtype=float, order="F")

In [7]:
y

array([[1.37068678e-311, 4.94065646e-324],
       [8.58465763e-315,             nan]])

In [10]:
y.flags['C']

False

In [11]:
y.flags['F']

True

In [13]:
np.ndarray(shape=(1,2), dtype=float, order="C")

array([[1.37070121e-311, 1.37069232e-311]])

In [14]:
np.ndarray(shape=(2,1), dtype=float, order="C")

array([[1.37070121e-311],
       [1.37069232e-311]])

In [15]:
np.ndarray(shape=(2,), dtype=float, order="C")

array([1.37070121e-311, 1.37069232e-311])

In [16]:
np.ndarray(shape=(2,), dtype=float, order="F")

array([1.37070121e-311, 1.37069232e-311])

In [ ]:
np.ndarray((2,))