## numpy.all

### numpy.all(a, axis=None, out=None, keepdims=< no value >)

### Test whether all array elements along a given axis evaluate to True.

In [1]:
import numpy as np

In [2]:
np.array([[True,False],[True, True]]).all()

False

In [3]:
np.all([[True,False],[True, True]]).all()

False

In [4]:
np.all([[True,False],[True, True]])

False

In [5]:
np.all([[True,False],[True, True]],  axis=0)

array([ True, False])

In [12]:
np.all([[True,False],[True, True]],  axis=1)

array([False,  True])

#### axis may be negative, in which case it counts from the last to the first axis.

In [73]:
np.all([[True,False],[True, True]],  axis=-1)

array([False,  True])

In [74]:
np.all([[True,False],[True, True]],  axis=-2)

array([ True, False])

In [15]:
np.all([[True,False],[True, True]],  axis=(0, 1))

False

In [22]:
np.all([[True,False],[True, True]],  axis=(0, -1))

False

In [38]:
np.all([[True,False],[True, True]],  axis=(1, -1)) #ValueError: duplicate value in 'axis'
np.all([[True,False],[True, True]],  axis=(-1, 1)) #ValueError: duplicate value in 'axis'
np.all([[True,False],[True, True]],  axis=(0, 1, -1)) #ValueError: duplicate value in 'axis'
np.all([[True,False],[True, True]],  axis=(0, -2)) #ValueError: duplicate value in 'axis'
np.all([[True,False],[True, True]],  axis=(1, -3)) #AxisError: axis -3 is out of bounds for array of dimension 2
np.all([[True,False],[True, True]],  axis=(1, 2)) #AxisError: axis -3 is out of bounds for array of dimension 2

ValueError: duplicate value in 'axis'

In [47]:
np.all([[True,False],[True, True]],  axis=(1, -2))

False

In [71]:
np.all([[True,True],[True, True]],  axis=(1, -2))

True

#### If this is a tuple of ints, a reduction is performed on multiple axes, instead of a single axis or all the axes as axis = None

In [50]:
np.all([[True,True],[True, True]],  axis=(0 ,1))

True

In [64]:
np.all([[True,True],[True, True]],  axis=(1, 0))

True

In [69]:
np.all([[[True,False],[True, True]], [[True,True],[True, True]]],  axis=(1, 0))

array([ True, False])

In [70]:
np.all([[[True,False],[True, True]], [[True,True],[True, True]]],  axis=(1, 0 , 2))

False

In [68]:
np.all([[[True,False],[True, True]], [[True,True],[True, True]]])

False

#### out arg  must have the same shape as the expected output and its type is preserved

In [40]:
out = np.ndarray((2,))
print(out)
np.all([[1,0], [1,1]],axis=0, out=out)

[4.94065646e-324 2.12199579e-314]


array([1., 0.])

In [41]:
out = np.ndarray((2,),dtype=int)
print(out)
results = np.all([[1,0], [1,1]],axis=0, out=out)

[0 0]


In [75]:
print(results);
out

[[ True False]]


array([ 359792784, 1912602624])

#### If this is set to True, the axes which are reduced are left in the result as dimensions with size one. With this option, the result will broadcast correctly against the input array.

In [45]:
np.all([[1,0], [1,1]],axis=0, keepdims= True)

array([[ True, False]])

In [62]:
np.all([[1,0], [1,1]],axis=0, keepdims= False)

array([ True, False])

In [86]:
x = np.all([[[True,False],[True, True]], [[True,True],[True, True]]],  keepdims=True)

In [87]:
print(x)
print(x.ndim)
print(x.shape)

[[[False]]]
3
(1, 1, 1)


#### Not a Number (NaN), positive infinity and negative infinity evaluate to True because these are not equal to zero

In [52]:
np.all([-1, 4, 5])

True

In [53]:
np.all([-1, 4, np.nan])

True

In [54]:
o=np.array(False)
z=np.all([-1, 4, 5], out=o)
id(z), id(o), z

(2281128872896, 2281128872896, array(True))

In [55]:
z is o, o is z

(True, True)

## ndarray.any

### Test whether any array element along a given axis evaluates to True. Returns single boolean unless axis is not None

In [76]:
np.any([[True, False], [True, True]])

True

In [58]:
np.any([[True,False],[True, True]],  axis=0)

array([ True,  True])

In [59]:
np.any([[True,False],[True, True]],  axis=0)

array([ True,  True])

In [60]:
np.any([-1, 0, 5])

True

In [61]:
np.any([-1, 0, np.nan])

True

## numpy.argmax

### numpy.argmax(a, axis=None, out=None)
### Returns the indices of the maximum values along an axis.

#### axis : int, optional - By default, the index is into the flattened array, otherwise along the specified axis.
#### out : array, optional - If provided, the result will be inserted into this array. It should be of the appropriate shape and dtype.
#### Returns - index_array : ndarray of ints

In [114]:
a = np.arange(6).reshape(2,3) + 10

In [115]:
a.argmax()

5

In [116]:
np.argmax(a)

5

In [117]:
a.argmax(axis=0)

array([1, 1, 1], dtype=int64)

In [118]:
a.argmax(axis=1)

array([2, 2], dtype=int64)

In [119]:
a

array([[10, 11, 12],
       [13, 14, 15]])

## numpy.amax

### numpy.amax(a, axis=None, out=None, keepdims=< no value >, initial=< no value >, where=< no value >)
### Return the maximum of an array or maximum along an axis.

#### Parameters:	
##### axis: Axis or axes along which to operate. By default, flattened input is used. If this is a tuple of ints, the maximum is selected over multiple axes, instead of a single axis or all the axes 
##### initial : scalar, optional - The minimum value of an output element. Must be present to allow computation on empty slice. See reduce for details.
##### where : array_like of bool, optional - Elements to compare for the maximum. See reduce for details.
#### Returns:	amax : ndarray or scalar
##### Maximum of a. If axis is None, the result is a scalar value. If axis is given, the result is an array of dimension a.ndim - 1.

In [88]:
a = np.arange(4).reshape((2,2))

In [89]:
np.amax(a)

3

In [95]:
np.amax(a , axis=0)

array([2, 3])

In [103]:
x = np.arange(27).reshape((3,3,3))

In [104]:
x

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [131]:
np.amax(x, keepdims=True)

array([[[26]]])

In [121]:
np.amax(x , axis=(0,1))

array([24, 25, 26])

In [122]:
np.amax(x , axis=(0,2))

array([20, 23, 26])

In [123]:
np.amax(x , axis=(1,0))

array([24, 25, 26])

In [124]:
np.amax(x , axis=(1))

array([[ 6,  7,  8],
       [15, 16, 17],
       [24, 25, 26]])

In [126]:
np.amax(x , axis=1)

array([[ 6,  7,  8],
       [15, 16, 17],
       [24, 25, 26]])

In [132]:
np.amax(x , axis=(1,), keepdims=True)

array([[[ 6,  7,  8]],

       [[15, 16, 17]],

       [[24, 25, 26]]])

In [133]:
np.amax(x , axis=(1,), keepdims=True ,initial=8)

array([[[ 8,  8,  8]],

       [[15, 16, 17]],

       [[24, 25, 26]]])

In [109]:
np.amax(x , axis=(0))

array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [128]:
np.amax(x , axis=(2))

array([[ 2,  5,  8],
       [11, 14, 17],
       [20, 23, 26]])

In [129]:
np.amax(x , axis=(1,0,2))

26

In [92]:
np.amax(a, where=[False, True], initial=-1, axis=1) # Expected result - array([-1,  3])

TypeError: amax() got an unexpected keyword argument 'where'

#### NaN values are propagated, that is if at least one item is NaN, the corresponding max value will be NaN as well. To ignore NaN values (MATLAB behavior), please use nanmax.

In [135]:
b = np.arange(5, dtype=float);b

array([0., 1., 2., 3., 4.])

In [136]:
b[2] = np.NAN;

In [137]:
np.amax(b)

E:\Study\ML\Anaconda\lib\site-packages\numpy\core\fromnumeric.py:83: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)


nan

In [141]:
#np.amax(b, where=~np.isnan(b), initial=-1); # output - 4
np.nanmax(b)

4.0

#### Don’t use amax for element-wise comparison of 2 arrays; when a.shape[0] is 2, maximum(a[0], a[1]) is faster than amax(a, axis=0).

In [142]:
c = np.arange(18).reshape(2,3,3)

In [143]:
c

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [145]:
np.amax(c, axis=0)

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [149]:
np.max([[-50], [10]], axis=-1, initial=5)

array([ 5, 10])

In [151]:
np.array([[-50], [10]])

array([[-50],
       [ 10]])

In [159]:
np.max([[-50], []], axis=-1, initial=5)

TypeError: '>=' not supported between instances of 'int' and 'list'

#### Notice that the initial value is used as one of the elements for which the maximum is determined, unlike for the default argument Python’s max function, which is only used for empty iterables

In [148]:
np.max([[], []], axis=-1, initial=5)

array([5., 5.])

In [158]:
max([[], []], default=5)

[]

In [155]:
max([[], [0]], default=5)

[0]

In [156]:
max([[0], [0]], default=5)

[0]

In [157]:
max([], default=5)

5

### amax - The maximum value of an array along a given axis, propagating any NaNs.
### amin - The minimum value of an array along a given axis, propagating any NaNs.
### nanmax - The maximum value of an array along a given axis, ignoring any NaNs.
### maximum - Element-wise maximum of two arrays, propagating any NaNs.
### fmax - Element-wise maximum of two arrays, ignoring any NaNs.
### argmax - Return the indices of the maximum values.
### nanmin, minimum, fmin

## numpy.unravel_index

### numpy.unravel_index(indices, shape, order='C')
### Converts a flat index or array of flat indices into a tuple of coordinate arrays.

#### Parameters:	
###### indices : array_like - An integer array whose elements are indices into the flattened version of an array of dimensions shape.
###### shape : tuple of ints - The shape of the array to use for unraveling indices.
###### order : {‘C’, ‘F’}, optional - Determines whether the indices should be viewed as indexing in row-major (C-style) or column-major (Fortran-style) order.
#### Returns : unraveled_coords : tuple of ndarray - Each array in the tuple has the same shape as the indices array.

In [166]:
np.unravel_index([22, 41, 37], (7,6))

(array([3, 6, 6], dtype=int64), array([4, 5, 1], dtype=int64))

In [172]:
a= np.arange(42).reshape(7,6) # index 22(element-22) is in 3rd row, 4th column

In [173]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41]])

In [169]:
np.array(np.arange(42),shape=(7,6))

TypeError: 'shape' is an invalid keyword argument for array()

In [170]:
np.unravel_index([22, 41, 37], (7,6), order="F")

(array([1, 6, 2], dtype=int64), array([3, 5, 5], dtype=int64))

In [174]:
a.T # index 22(element-9) is in 1st column, 3rd row

array([[ 0,  6, 12, 18, 24, 30, 36],
       [ 1,  7, 13, 19, 25, 31, 37],
       [ 2,  8, 14, 20, 26, 32, 38],
       [ 3,  9, 15, 21, 27, 33, 39],
       [ 4, 10, 16, 22, 28, 34, 40],
       [ 5, 11, 17, 23, 29, 35, 41]])

## numpy.ravel_multi_index

### numpy.ravel_multi_index(multi_index, dims, mode='raise', order='C')
### Converts a tuple of index arrays into an array of flat indices, applying boundary modes to the multi-index.

#### Parameters:	
##### multi_index : tuple of array_like - A tuple of integer arrays, one array for each dimension.
##### dims : tuple of ints - The shape of array into which the indices from multi_index apply.
##### mode : {‘raise’, ‘wrap’, ‘clip’}, optional - Specifies how out-of-bounds indices are handled. Can specify either one mode or a tuple of modes, one mode per index.
‘raise’ – raise an error (default)
‘wrap’ – wrap around
‘clip’ – clip to the range
In ‘clip’ mode, a negative index which would normally wrap will clip to 0 instead.

##### order : {‘C’, ‘F’}, optional - Determines whether the multi-index should be viewed as indexing in row-major (C-style) or column-major (Fortran-style) order.

#### Returns: raveled_indices : ndarray - An array of indices into the flattened version of an array of dimensions dims.

In [6]:
arr = np.array([[3,6,6],[4,5,1]])
np.ravel_multi_index(arr, (7,6))

array([22, 41, 37], dtype=int64)

In [7]:
np.ravel_multi_index(arr, (7,6), order="F")

array([31, 41, 13], dtype=int64)

In [10]:
np.ravel_multi_index(np.array([[3,6,6],[4,5,1]]), (7,6), order="F")

array([31, 41, 13], dtype=int64)

In [11]:
np.ravel_multi_index([[3,6,6],[4,5,1]], (7,6), order="F")

array([31, 41, 13], dtype=int64)

In [12]:
np.ravel_multi_index([[3,6,6],[4,5,1]], (7,6), order="F", mode="clip")

array([31, 41, 13], dtype=int64)

In [24]:
np.ravel_multi_index((3,6,6,6),(4,5,1,2))

ValueError: invalid entry in coordinates array

In [30]:
np.ravel_multi_index((3,1,4,1), (6,7,8,9))

1621

In [31]:
np.ravel_multi_index(((3,1,4,1), (6,7,8,9)))

TypeError: Required argument 'dims' (pos 2) not found

In [18]:
np.ravel_multi_index(arr, (4,4), mode=('clip','wrap')) # clip mode will clip the extra indexes to zero i.e. if index is greater than the shape of that dimention it will clip to the last index

array([12, 13, 13], dtype=int64)

In [19]:
np.ravel_multi_index(arr, (4,4), mode=('clip'))

array([15, 15, 13], dtype=int64)

In [21]:
np.ravel_multi_index(arr, (4,4), mode=('wrap')) # warap mode will again start the index from zero if index exceed the shape

array([12,  9,  9], dtype=int64)

In [32]:
np.ravel_multi_index(arr, (4,4), mode=('wrap','clip'))

array([15, 11,  9], dtype=int64)

In [40]:
np.arange(16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [41]:
print(arr) #(3,4)-(3,3+1(-1))-12 ,(6,5)-(3+3, 3+2)-9,(6,1)-9

[[3 6 6]
 [4 5 1]]


In [25]:
np.ravel_multi_index(arr, (4,4))

ValueError: invalid entry in coordinates array

In [28]:
np.ravel_multi_index(arr)

TypeError: Required argument 'dims' (pos 2) not found

## numpy.argpartition

### numpy.argpartition(a, kth, axis=-1, kind='introselect', order=None)
#### Perform an indirect partition along the given axis using the algorithm specified by the kind keyword. It returns an array of indices of the same shape as a that index data along the given axis in partitioned order.

In [42]:
a = np.array([3, 4, 2, 1])

In [73]:
indices = np.argpartition(a, 3)
print(indices)
print(a[indices])

[2 3 0 1]
[2 1 3 4]


In [76]:
#indices = np.argpartition(a, 4)#ValueError: kth(=4) out of bounds (4)
indices = np.argpartition(a, 1)
print(indices)
print(a[indices])

[3 2 1 0]
[1 2 4 3]


In [55]:
indices = np.argpartition(a, [3,1]) #indices = np.argpartition(a, (3,1)) #kth : int or sequence of ints
print(indices)
print(a[indices])

[3 2 0 1]
[1 2 3 4]


In [56]:
x = [3, 4, 2, 1]
np.array(x)[np.argpartition(x, 3)]

array([2, 1, 3, 4])

In [63]:
y = np.random.randint(5, 10, 15).reshape(3,5)
y

array([[9, 8, 6, 6, 5],
       [7, 8, 5, 6, 5],
       [8, 5, 8, 7, 7]])

In [64]:
np.argpartition(y, (3,7,10)) #ValueError: kth(=7) out of bounds (5)
# np.argpartition(y, (3,7,10) , axis=1) #ValueError: kth(=7) out of bounds (5)
#np.argpartition(y, (3,7,10) , axis=0) #ValueError: kth(=3) out of bounds (3)

ValueError: kth(=7) out of bounds (5)

In [65]:
np.argpartition(y, (3,7,10) , axis=None)

array([ 9,  4, 11,  7,  8,  2,  3, 13, 14,  5, 10,  6, 12,  1,  0],
      dtype=int64)

In [72]:
indices = np.argpartition(y, (1) , axis=0) # across the row
print(y)
print(indices)
print(y[indices])

[[9 8 6 6 5]
 [7 8 5 6 5]
 [8 5 8 7 7]]
[[1 2 1 0 0]
 [2 1 0 1 1]
 [0 0 2 2 2]]
[[[7 8 5 6 5]
  [8 5 8 7 7]
  [7 8 5 6 5]
  [9 8 6 6 5]
  [9 8 6 6 5]]

 [[8 5 8 7 7]
  [7 8 5 6 5]
  [9 8 6 6 5]
  [7 8 5 6 5]
  [7 8 5 6 5]]

 [[9 8 6 6 5]
  [9 8 6 6 5]
  [8 5 8 7 7]
  [8 5 8 7 7]
  [8 5 8 7 7]]]


In [ ]:
y